workflows:
  build_kivy_apk:
    name: Build Kivy APK
    environment:
      groups:
        - kivy_android
      vars:
        PACKAGE_NAME: "com.example.pong"
    scripts:
      - name: Build APK
        script: |
          pip install buildozer
          buildozer android debug
    artifacts:
      - bin/*.apk
