workflows:
  build_kivy_apk:
    name: Pong Kivy Build
    max_build_duration: 30
    environment:
      docker: kivy/buildozer  # Imagen oficial
      vars:
        BUILD_TYPE: release
    scripts:
      - name: Instalar dependencias y compilar APK
        script: |
          pip install --upgrade pip
          buildozer android $BUILD_TYPE
    artifacts:
      - build/*.apk
    publishing:
      email:
        recipients:
          - tu_correo@ejemplo.com
        notify:
          success: true
          failure: true
